### PR TITLE
Moving Guppy to Github Actions 

### PR DESCRIPTION
**Pull request by cmlsn**
### New Features

- Moving Guppy to Github Actions for Build, Security pipelines, and NPM unit tests.
- Adding NPM specific input variables
- Removing Travis.yaml

### CODE REVIEW

**Comment by cmlsn** [comment]
After the review, we will need to remove the travis branch protections before merging since these have been removed in this push.

**Review by m0nhawk — APPROVED** [review]
Cool. 👍

**Comment by ocshawn** [comment]
is this still needed? if not please close

**Comment by ocshawn** [comment]
please reopen if this is still needed

**Pull request closed without merging**
