### PR TITLE
PXP-9144 ConnectedFilter: allow specifying extra fields to query

### PR DESCRIPTION
**Pull request by paulineribeyre**
Jira Ticket: [PXP-9144](https://ctds-planx.atlassian.net/browse/PXP-9144)

### Improvements
- ConnectedFilter: allow specifying extra fields to query aggregated data for

### CODE REVIEW

**Review by mfshao — DISMISSED** [review]
very cool! please update the version number in `package.json` so you can make an npm release later

**Comment by mfshao** [comment]
could you do a `npm i` and commit the lock as well?

**Comment by paulineribeyre** [comment]
woops! sure

**Comment by mfshao** [comment]
hmmm do you still have `npm@6` locally? npm 6->7 has introduced a new peer dependency resolution logic so their lock files are in different format

could you `npm i -g npm@7` and then regenerate the lock? sorry about these hassles 😅

**Comment by paulineribeyre** [comment]
thank you @mfshao, sorry about that - fixed

**Review by mfshao — APPROVED** [review]

**Pull request merged**
